services:
  database:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - taskify_network
    restart: always

  client:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3457:80
    networks:
      - taskify_network
    restart: always

volumes:
  db_data:

networks:
  taskify_network: 
    driver: bridge